services:
  - type: web
    name: Footelly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
  - type: sqlite
    name: database.db
    plan: free
