services:
  - type: web
    name: Footelly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///database.db

